defaults:
 - /datamodule/dataset/cells/cell-template@Reed360
 - /datamodule/dataset/species/human@Reed360.genome

Reed360:

  bin_target: 'atacpeak'

  data_types: 

    atacsignal:
      # Lab: 
      # GEO Accession: 
      # UCSC Accession: 
      source: 
        url: file://${data_dir}/raw/human/Reed360/atacsignal/0360_edger.bw
        md5: null
        

    atacpeak:
      # Lab: 
      # GEO Accession: 
      # UCSC Accession: 
      source: 
        url: file://${data_dir}/raw/human/Reed360/atacpeak/0360_dedup.bed
        md5: null

    
    # Cell line is only used for prediction. Skip TF data
    ctcfpeak: null
    sp1peak: null
    yy1peak: null
