# default
  print_freq: 10000  # in number of steps
  seed: 1337
  wandb_log: False
  run_name: paper-hg38-map-concat-stage1024-rf-lrelu-eval-stg-newsplit-newdata-atac-var-beta-neg-s1337  # name of the run

# data paths
  train_dir: data/processed_data/train_dataset.npz          # training data
  val_dir: data/processed_data/val_dataset.npz              # validation data for evaluation
  test_dir: data/processed_data/hepg2_input.npz             # test data for evaluation
  logs_dir: checkpoints/stage2_models_gm12878_k562_all      # directory where model checkpoints will be saved
  stage_1_model: checkpoints/stage1_gm12878_k562_model.pth  # path to stage-1 model

# stage-1 model parameters:
  ksizes: [11, 11, 11, 5, 5]
  channels: [5, 30, 60, 60, 90, 90, 90, 4]
  poolings: [4, 5, 5, 4, 2]
  
# stage-2 training:
  n_epochs: 20
  batch_size: 32
  n_feat: 180
  seq_len: 401
  binning: 1000
  dropout: 0.1
  num_heads: 4
  num_layers: 4
  embed_dim: 32
  hidden_dim: 96
  lr: 0.001
  log_scale: True           # log scale the target
  
  ATTENTION: False
  RELATIVE_POSITIONS: False
  META: False
  MAP: True
  ATAC: True

  num_workers: 8

# Uncertainty estimation
  var_flg: True
  beta: 0.5

# Feature selection
  STG: True
  stg_reg: 0.01
  input_feat_dims: [7500, 3000, 600, 180, 90]
  
# PE hyperparams:
  pe_res: 500
  max_len: 12001
  PEU: True

# eval options:
  save_res: True    # save results
  res_dir: results/ # directory where results will be saved
  log_strat_dist_plot: False
