# default
  print_freq: 10000                                         # print frequency in number of steps
  seed: 1337                                                # random seed
  wandb_log: False                                          # wandb logging
  run_name: paper-hg38-map-concat-stage1024-rf-lrelu-eval-stg-newsplit-newdata-atac-var-beta-neg-s1337 
                                                            # name of the run

# data generation or paths if exist for training/testing
  hic_res: 5000                                             # hic resolution [bp]
  hic_path: data/hic/                                       # hic data path
  atac_path: data/stage1_outputs/                           # DNA and ATAC path
  cell_lines_train: ["gm12878", "k562"]                     # training cell lines
  cell_lines_val: ["gm12878", "k562"]                       # validation cell lines
  cell_lines_test: hepg2                                    # test cell lines
  chroms: null                                              # if null, default chromosomes split is used
                                                            # here one can specify chromosomes for test, e.g. chroms: [2, 6, 19]

  data_save_dir: null                                       # if not null, path where data will be saved and it creates
                                                            # {cell_line}_{train/test/val}.npz and {train/val}_dataset.py
                                                            # if multiple cell lines are used for training and validation

  train_dir: null                                           # training data path if exists, e.g. data/processed_data/train_dataset.npz
  val_dir: null                                             # validation data path if exists
  test_dir: null                                            # test data path if exists, e.g. data/processed_data/hepg2_input.npz
  logs_dir: checkpoints                                     # directory where model checkpoints will be saved
  stage_1_model: checkpoints/stage1_model_gm12878_k562.pth  # path to stage-1 model

# stage-1 model parameters:
  ksizes: [11, 11, 11, 5, 5]                                # CNN layer kernel sizes
  channels: [5, 30, 60, 60, 90, 90, 90, 4]                  # CNN layer channel dimensions
  poolings: [4, 5, 5, 4, 2]                                 # CNN layer pooling sizes
  
# stage-2 training parameters:
  n_epochs: 20                                              # training epoches
  batch_size: 32                                            # batch size
  n_feat: 180                                               # projection dimension of stage-1 features
  seq_len: 401                                              # number of ATAC peaks
  binning: 1000                                             # ATAC peak region length [bp]
  dropout: 0.1                                              # dropout rate
  num_heads: 4                                              # number of attention heads
  num_layers: 4                                             # number of attention layers
  embed_dim: 32                                             # embedding dimension d_model
  hidden_dim: 96                                            # hidden dimension of transformer, multiple of embed_dim
  lr: 0.001                                                 # learning rate
  log_scale: True                                           # log scale the target
  
  ATTENTION: False                                          # get attention weights [not implemented]
  RELATIVE_POSITIONS: False                                 # relative positional encoding [deprecated]
  META: False                                               # use meta information for relative PE [deprecated]
  MAP: True                                                 # add mappability track
  ATAC: True                                                # add ATAC track

  num_workers: 8                                            # number of workers for data loader

# Uncertainty estimation
  var_flg: True                                             # enable aleatoric uncertainty estimation
  beta: 0.5                                                 # hyperparamter for beta-NLL loss

# Feature selection
  STG: True                                                 # enable feature selection; if false, the 2. last CNN layer is selected
  stg_reg: 0.01                                             # feature sparisity regularization
  input_feat_dims: [7500, 3000, 600, 180, 90]               # dimension of the CNN feature set
  
# Positional encoding hyperparams:
  pe_res: 500                                               # encoding resolution of genome-distance-aware PE [bp]
  max_len: 12001                                            # maximum encoding sequence length [peak]
  PEU: True                                                 # enable PE upscaling

# eval options:
  save_res: True                                            # save results
  res_dir: results/                                         # directory where results will be saved
  log_strat_dist_plot: False                                # log distance stratified plot in wandb
